apiVersion: v1
kind: Secret
metadata:
  name: educonnect-secrets
  namespace: educonnect
  labels:
    {{- include "educonnect.labels" . | nindent 4 }}
type: Opaque
stringData:
  # MongoDB Atlas Connection String
  MONGODB_URI: {{ .Values.global.mongodb.uri | quote }}

  # AWS Credentials
  AWS_ACCESS_KEY_ID: {{ .Values.global.aws.accessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.global.aws.secretAccessKey | quote }}
  AWS_S3_BUCKET: {{ .Values.global.aws.s3Bucket | quote }}
  AWS_SQS_QUEUE_URL: {{ .Values.global.aws.sqsQueueUrl | quote }}
  AWS_SES_SENDER_EMAIL: {{ .Values.global.aws.sesSenderEmail | quote }}

  # AI API Keys
  GEMINI_API_KEY: {{ .Values.global.ai.geminiApiKey | quote }}
  DEEPSEEK_API_KEY: {{ .Values.global.ai.deepseekApiKey | quote }}

  # Frontend Cognito Client Secret
  {{- if .Values.frontend.env.viteAwsClientSecret }}
  VITE_AWS_CLIENT_SECRET: {{ .Values.frontend.env.viteAwsClientSecret | quote }}
  VITE_AWS_CLIENT_ID: {{ .Values.frontend.env.viteAwsClientId | quote }}
  {{- end }}